package me.ftmc.message

enum class MessageType {
  HELLO,
  HEART_BEAT,
  ROOM_COMMAND_RESULT,
  ROOM_CONFIG_EDIT_RESULT,
  RECORD_COMMAND_RESULT,
  LIVE_STATE_CHANGE,
  RECORD_STATE_CHANGE,
  GLOBAL_CONFIG_EDIT_RESULT,
  LOGIN_STATE_CHANGE,
  BYE
}