package me.ftmc.message

enum class MessageType {
  HELLO,
  HEART_BEAT,
  ROOM_ADD,
  ROOM_DEL,
  ROOM_LIST,
  ROOM_CONFIG_EDIT_RESULT,
  LIVE_START,
  LIVE_STOP,
  RECORD_START,
  RECORD_STOP,
  GLOBAL_CONFIG_EDIT_RESULT,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  LOGIN_QR_CODE_CHANGE,
  LOGIN_QR_SCAN,
  BYE
}